name: hdb-explorer
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - streamlit
  - pandas
  - numpy
  - plotly
  - folium
  - pip
  - pip:
      - streamlit-folium
      - pyarrow
